# Generated by Django 6.0.1 on 2026-02-09 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='사업장 메모'),
        ),
    ]
