# Generated by Django 6.0.1 on 2026-02-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='branch_type',
            field=models.CharField(choices=[('main', '본점'), ('branch', '지점')], db_index=True, default='main', max_length=10),
        ),
    ]
