# Generated by Django 6.0.1 on 2026-02-11 00:42

from django.db import migrations, models

def populate_branch_codes(apps, schema_editor):
    """기존 Business에 branch_code 채우기"""
    Business = apps.get_model('businesses', 'Business')
    
    # 사용자별, 사업자번호별로 그룹화
    businesses = Business.objects.all().order_by('user', 'registration_number', 'created_at')
    
    current_user = None
    current_reg_num = None
    counter = 1
    
    for business in businesses:
        # 새로운 사용자 or 새로운 사업자번호
        if (business.user_id != current_user or 
            business.registration_number != current_reg_num):
            current_user = business.user_id
            current_reg_num = business.registration_number
            counter = 1
        
        business.branch_code = str(counter).zfill(4)
        business.save(update_fields=['branch_code'])
        counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),  # 실제 최신 마이그레이션 번호로
    ]

    operations = [
        # 1. branch_code 필드 추가 (nullable)
        migrations.AddField(
            model_name='business',
            name='branch_code',
            field=models.CharField(
                max_length=4,
                default='0001',
                verbose_name='분류코드',
                null=True,
                blank=True
            ),
        ),
        
        # 2. 기존 데이터에 branch_code 채우기
        migrations.RunPython(populate_branch_codes, migrations.RunPython.noop),
        
        # 3. branch_code를 NOT NULL로 변경
        migrations.AlterField(
            model_name='business',
            name='branch_code',
            field=models.CharField(
                max_length=4,
                default='0001',
                verbose_name='분류코드',
                null=False
            ),
        ),
        
        # 4. UniqueConstraint 추가
        migrations.AddConstraint(
            model_name='business',
            constraint=models.UniqueConstraint(
                fields=['user', 'registration_number', 'branch_code'],
                condition=models.Q(is_active=True),
                name='unique_active_business_registration'
            ),
        ),
    ]
