# Generated by Django 6.0.1 on 2026-02-11 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_business_memo'),
        ('businesses', '0003_add_branch_code'),
    ]

    operations = [
    ]
