# Generated by Django 6.0.1 on 2026-02-11 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_merge_0002_business_memo_0003_add_branch_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='business',
            name='unique_active_business_registration',
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='활성 상태'),
        ),
        migrations.AlterField(
            model_name='business',
            name='branch_code',
            field=models.CharField(default='0001', help_text='같은 사업자번호의 사업장 구분 (0001~9999)', max_length=4, verbose_name='분류코드'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='활성 상태'),
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, help_text='000-00-00000 형식', max_length=12, verbose_name='사업자등록번호'),
        ),
    ]
