# Generated by Django 6.0.1 on 2026-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_remove_business_unique_active_business_registration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='branch_code',
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
