# Generated by Django 6.0.1 on 2026-02-01 06:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_registration_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='사업자등록번호는 10자리 숫자여야 합니다', regex='^\\d{10}$')])),
                ('business_type', models.CharField(blank=True, choices=[('individual', '개인사업자'), ('corporate', '법인사업자')], max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='올바른 전화번호를 입력하세요', regex='^[0-9\\-\\+\\(\\)\\s]+$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
