# Generated by Django 6.0.1 on 2026-02-07 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='business_registration_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='사업자등록번호는 10자리 숫자여야 합니다', regex='^\\d{10}$')]),
        ),
    ]
