# Generated by Django 6.0.1 on 2026-02-11 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='business_registration_number',
        ),
    ]
