# Generated by Django 6.0.1 on 2026-02-01 06:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], db_index=True, max_length=20)),
                ('expense_type', models.CharField(blank=True, choices=[('salary', '인건비'), ('rent', '임차료'), ('advertising', '광고선전비'), ('supplies', '소모품비'), ('entertainment', '접대비'), ('communication', '통신비'), ('utilities', '전기·수도·가스비'), ('repair', '수선비'), ('vehicle', '차량유지비'), ('insurance', '보험료'), ('tax', '세금과공과'), ('other', '기타 경비')], db_index=True, max_length=30, null=True)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('business_number', models.CharField(blank=True, db_index=True, max_length=12)),
                ('contact', models.CharField(blank=True, max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchants',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tx_type', models.CharField(choices=[('IN', '수입'), ('OUT', '지출')], db_index=True, max_length=10)),
                ('tax_type', models.CharField(choices=[('taxable', '과세 (부가세 10%)'), ('tax_free', '면세'), ('zero_rated', '영세율 (수출)')], db_index=True, default='taxable', max_length=20)),
                ('is_business', models.BooleanField(db_index=True, default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('merchant_name', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='businesses.account')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='businesses.business')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='transactions.category')),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.merchant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=[('receipt', '영수증'), ('tax_invoice', '세금계산서'), ('simple_receipt', '간이영수증')], default='receipt', max_length=20)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('original_name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='transactions.transaction')),
            ],
            options={
                'db_table': 'attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['type', 'order'], name='categories_type_b2e241_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='categories_user_id_418e53_idx'),
        ),
        migrations.AddIndex(
            model_name='merchant',
            index=models.Index(fields=['user', 'is_active', 'name'], name='merchants_user_id_149faf_idx'),
        ),
        migrations.AddConstraint(
            model_name='merchant',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'name'), name='unique_active_merchant_name_per_user'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', '-occurred_at'], name='transaction_user_id_2b2960_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_business', '-occurred_at'], name='transaction_user_id_d43d13_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'tax_type', '-occurred_at'], name='transaction_user_id_8ff6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'tx_type', '-occurred_at'], name='transaction_user_id_4b7efa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['business', '-occurred_at'], name='transaction_busines_773248_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-occurred_at'], name='transaction_account_a37b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_business', 'tax_type', 'occurred_at'], name='transaction_user_id_8575df_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('vat_amount__gte', 0), ('vat_amount__isnull', True), _connector='OR'), name='transaction_vat_non_negative'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['user', '-uploaded_at'], name='attachments_user_id_3f5f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['transaction'], name='attachments_transac_05eb06_idx'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(('size__lte', 5242880)), name='attachment_file_size_limit'),
        ),
    ]
