# Generated by Django 6.0.1 on 2026-02-11 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='활성 상태'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='활성 상태'),
        ),
    ]
