# Generated by Django 6.0.1 on 2026-02-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='income_type',
            field=models.CharField(blank=True, choices=[('sales', '매출'), ('service', '용역수입'), ('interest', '이자수입'), ('rental', '임대수입'), ('investment', '투자수익'), ('other', '기타 수입')], db_index=True, max_length=30, null=True),
        ),
    ]
