# Generated by Django 6.0.1 on 2026-02-07 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_category_income_type'),
        ('transactions', '0004_seed_system_categories'),
    ]

    operations = [
    ]
