# Generated by Django 6.0.1 on 2026-02-06 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_merge_20260206_1810'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'merchant_categories',
            },
        ),
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merchants', to='transactions.merchantcategory'),
        ),
        migrations.AddConstraint(
            model_name='merchantcategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_merchant_category_per_user'),
        ),
    ]
