# Generated by Django 6.0.1 on 2026-02-06 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_merchantcategory_alter_merchant_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='merchantcategory',
            name='unique_merchant_category_per_user',
        ),
        migrations.AlterField(
            model_name='merchantcategory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='merchantcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='unique_merchant_category_per_user'),
        ),
        migrations.AddConstraint(
            model_name='merchantcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('name',), name='unique_global_merchant_category_name'),
        ),
    ]
